services:
  - type: web
    name: ai-kisan-salahkar-backend
    runtime: node
    rootDir: server
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
  - type: web
    name: ai-kisan-salahkar-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start

