/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments.index'
import { Route as ExperimentsNewRouteImport } from './routes/experiments.new'
import { Route as ExperimentsExperimentIdRouteImport } from './routes/experiments.$experimentId'
import { Route as ExperimentsExperimentIdReportRouteImport } from './routes/experiments.$experimentId.report'

const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/experiments/',
  path: '/experiments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsNewRoute = ExperimentsNewRouteImport.update({
  id: '/experiments/new',
  path: '/experiments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsExperimentIdRoute = ExperimentsExperimentIdRouteImport.update({
  id: '/experiments/$experimentId',
  path: '/experiments/$experimentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsExperimentIdReportRoute =
  ExperimentsExperimentIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => ExperimentsExperimentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/schemes': typeof SchemesRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRouteWithChildren
  '/experiments/new': typeof ExperimentsNewRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/experiments/$experimentId/report': typeof ExperimentsExperimentIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/schemes': typeof SchemesRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRouteWithChildren
  '/experiments/new': typeof ExperimentsNewRoute
  '/experiments': typeof ExperimentsIndexRoute
  '/experiments/$experimentId/report': typeof ExperimentsExperimentIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/schemes': typeof SchemesRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRouteWithChildren
  '/experiments/new': typeof ExperimentsNewRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/experiments/$experimentId/report': typeof ExperimentsExperimentIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/learn'
    | '/login'
    | '/profile'
    | '/schemes'
    | '/experiments/$experimentId'
    | '/experiments/new'
    | '/experiments/'
    | '/experiments/$experimentId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/learn'
    | '/login'
    | '/profile'
    | '/schemes'
    | '/experiments/$experimentId'
    | '/experiments/new'
    | '/experiments'
    | '/experiments/$experimentId/report'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/learn'
    | '/login'
    | '/profile'
    | '/schemes'
    | '/experiments/$experimentId'
    | '/experiments/new'
    | '/experiments/'
    | '/experiments/$experimentId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SchemesRoute: typeof SchemesRoute
  ExperimentsExperimentIdRoute: typeof ExperimentsExperimentIdRouteWithChildren
  ExperimentsNewRoute: typeof ExperimentsNewRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/experiments'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/new': {
      id: '/experiments/new'
      path: '/experiments/new'
      fullPath: '/experiments/new'
      preLoaderRoute: typeof ExperimentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/$experimentId': {
      id: '/experiments/$experimentId'
      path: '/experiments/$experimentId'
      fullPath: '/experiments/$experimentId'
      preLoaderRoute: typeof ExperimentsExperimentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/$experimentId/report': {
      id: '/experiments/$experimentId/report'
      path: '/report'
      fullPath: '/experiments/$experimentId/report'
      preLoaderRoute: typeof ExperimentsExperimentIdReportRouteImport
      parentRoute: typeof ExperimentsExperimentIdRoute
    }
  }
}

interface ExperimentsExperimentIdRouteChildren {
  ExperimentsExperimentIdReportRoute: typeof ExperimentsExperimentIdReportRoute
}

const ExperimentsExperimentIdRouteChildren: ExperimentsExperimentIdRouteChildren =
  {
    ExperimentsExperimentIdReportRoute: ExperimentsExperimentIdReportRoute,
  }

const ExperimentsExperimentIdRouteWithChildren =
  ExperimentsExperimentIdRoute._addFileChildren(
    ExperimentsExperimentIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SchemesRoute: SchemesRoute,
  ExperimentsExperimentIdRoute: ExperimentsExperimentIdRouteWithChildren,
  ExperimentsNewRoute: ExperimentsNewRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
